.TH SMAN 1
.SH Name
sman\-VERSION \- simple system package manager
.SH SYNOPSYS
.B sman
[\fBoptions\fR]
.IR command
[arguments]
.SH DESCRIPTION
.B sman
manages system packages
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show command usage
.TP
.BR \-c ", " \-\-config
Select a different config file
.SH COMMANDS
.TP
.BR add
Add a package to the world set and install it
